"""Initial migration

Revision ID: c0f5d059b8b5
Revises: 
Create Date: 2026-07-29 13:07:49.822142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f5d059b8b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('handle', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('rss_monitoring', sa.Boolean(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('external_links', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_queue',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.create_index('idx_queue_status_priority', ['status', 'priority', 'created_at'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_extract_transcript', sa.Boolean(), nullable=True),
    sa.Column('auto_extract_comments', sa.Boolean(), nullable=True),
    sa.Column('auto_extract_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('max_comments_per_video', sa.Integer(), nullable=True),
    sa.Column('default_video_quality', sa.String(length=20), nullable=True),
    sa.Column('default_audio_format', sa.String(length=20), nullable=True),
    sa.Column('default_audio_quality', sa.String(length=20), nullable=True),
    sa.Column('max_concurrent_downloads', sa.Integer(), nullable=True),
    sa.Column('ytdlp_player_client', sa.String(length=20), nullable=True),
    sa.Column('ytdlp_rate_limit', sa.String(length=20), nullable=True),
    sa.Column('ytdlp_proxy', sa.String(length=255), nullable=True),
    sa.Column('cookies_file_path', sa.String(length=500), nullable=True),
    sa.Column('rss_poll_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('snapshot_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_channel_snapshots_range', ['channel_id', 'snapshot_date'], unique=False)

    op.create_table('playlists',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('live_status', sa.String(length=20), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=True),
    sa.Column('age_limit', sa.Integer(), nullable=True),
    sa.Column('has_transcript', sa.Boolean(), nullable=True),
    sa.Column('comments_disabled', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('formats', sa.Text(), nullable=True),
    sa.Column('chapters', sa.Text(), nullable=True),
    sa.Column('heatmap', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index('idx_videos_channel_shorts', ['channel_id', 'is_short'], unique=False)
        batch_op.create_index('idx_videos_channel_upload', ['channel_id', 'upload_date'], unique=False)
        batch_op.create_index('idx_videos_channel_views', ['channel_id', 'view_count'], unique=False)

    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=50), nullable=True),
    sa.Column('author_thumbnail', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('author_is_creator', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('download_type', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.create_index('idx_downloads_video_type', ['video_id', 'download_type', 'status'], unique=False)

    op.create_table('playlist_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.String(length=50), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('segments', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_video_snapshots_range', ['video_id', 'snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_video_snapshots_range')

    op.drop_table('video_snapshots')
    op.drop_table('transcripts')
    op.drop_table('playlist_videos')
    with op.batch_alter_table('download_history', schema=None) as batch_op:
        batch_op.drop_index('idx_downloads_video_type')

    op.drop_table('download_history')
    op.drop_table('comments')
    op.drop_table('ai_analysis')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index('idx_videos_channel_views')
        batch_op.drop_index('idx_videos_channel_upload')
        batch_op.drop_index('idx_videos_channel_shorts')

    op.drop_table('videos')
    op.drop_table('playlists')
    with op.batch_alter_table('channel_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_channel_snapshots_range')

    op.drop_table('channel_snapshots')
    op.drop_table('user_settings')
    op.drop_table('search_history')
    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.drop_index('idx_queue_status_priority')

    op.drop_table('processing_queue')
    op.drop_table('channels')
    # ### end Alembic commands ###
