"""increase_target_id_length

Revision ID: cc6d68dead72
Revises: c0f5d059b8b5
Create Date: 2026-07-29 13:21:37.831019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc6d68dead72'
down_revision = 'c0f5d059b8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_queue', schema=None) as batch_op:
        batch_op.alter_column('target_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
